Frontend:
  impl: LoadStoreTrace
  # impl: SimpleO3
  clock_ratio: 8
  # num_expected_insts: 200000
  # llc_capacity_per_core: 1MB
  # llc_num_mshr_per_core: 1
  path: ../ld_st_trace.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR3
    org:
      preset: DDR3_4Gb_x128
      channel: 1
      rank: 1
    timing:
      preset: DDR3_1600J

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:
      # - ControllerPlugin:
          # impl: TraceRecorder
          # path: ./example_dram.trace

  # view the address mapping
  AddrMapper:
    impl: RoBaRaCoCh