Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 2000000
  llc_capacity_per_core: 1KB # Should be set as no cache, but this is a workaround
  traces:
    - /root/user/3D_DRAM_MODELING_MASTER/ramulator2/traces/high-mem-intensity.trace


  Translation:
    impl: RandomTranslation
    max_addr: 2199015689679


MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR4
    drampower_enable: true # This can enable dram power model
    voltage:
      preset: Default #
    current:
      preset: Default

    org:
      preset: DDR4_8Gb_x8
      channel: 2
      rank: 1
    timing:
      preset: DDR4_2400R

  Controller:
    impl: Generic
    Scheduler:
      impl: FCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    impl: RoBaRaCoCh