Frontend:
  impl: LoadStoreTrace
  # impl: SimpleO3
  clock_ratio: 8
  # num_expected_insts: 200000
  # llc_capacity_per_core: 1MB
  # llc_num_mshr_per_core: 1
  path: ../ld_st_trace.trace

  Translation:
    impl: RandomTranslation
    max_addr: 2147483648

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3


  DRAM:
    impl: DDR4

    drampower_enable: true # This can enable dram power model
    structure_type: 2
    # The preset of DRAM voltage and current must be specified, also the preset for power modeling has to exists within.
    voltage:
      preset: Default # Sets to Default to enable basic voltage adjustment
    current:
      preset: Default

    org:
      preset: DDR4_1Gb_x128
      channel: 1
      rank: 1
    timing:
      preset: DDR4_3DDRAM_128

  Controller:
    impl: Generic
    Scheduler:
      impl: FCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  # view the address mapping
  AddrMapper:
    impl: RoBaRaCoCh
